### ISSUE TITLE
Rails 5 Upgrade: Running into issues with ExecJS

### ISSUE THREAD

**Issue by Schwad** [rails/execjs#51]
I have been upgrading one of my larger applications to Rails 5 this week, and have hit a pretty big wall when trying to fire up my server involving ExecJS, here's from better_errors:

```ruby
ExecJS::RuntimeError at /users/sign_in
SyntaxError: [stdin]:15:19: missing / (unclosed regex)
```

Stacktrace:

```ruby
ExecJS::RuntimeError - SyntaxError: [stdin]:15:19: missing / (unclosed regex):
  sprockets (4.0.0.beta2) lib/sprockets/directive_processor.rb:178:in `rescue in block in process_directives'
  sprockets (4.0.0.beta2) lib/sprockets/directive_processor.rb:175:in `block in process_directives'
  sprockets (4.0.0.beta2) lib/sprockets/directive_processor.rb:174:in `process_directives'
  sprockets (4.0.0.beta2) lib/sprockets/directive_processor.rb:79:in `_call'
  sprockets (4.0.0.beta2) lib/sprockets/directive_processor.rb:64:in `call'
  sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:83:in `call_processor'
  sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:65:in `block in call_processors'
  sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:64:in `call_processors'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:147:in `load_from_unloaded'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:58:in `block in load'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:323:in `fetch_asset_from_dependency_cache'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:42:in `load'
  sprockets (4.0.0.beta2) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (4.0.0.beta2) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (4.0.0.beta2) lib/sprockets/bundle.rb:23:in `block in call'
  sprockets (4.0.0.beta2) lib/sprockets/utils.rb:152:in `dfs'
  sprockets (4.0.0.beta2) lib/sprockets/bundle.rb:24:in `call'
  sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:83:in `call_processor'
  sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:65:in `block in call_processors'
  sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:64:in `call_processors'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:147:in `load_from_unloaded'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:58:in `block in load'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:323:in `fetch_asset_from_dependency_cache'
  sprockets (4.0.0.beta2) lib/sprockets/loader.rb:42:in `load'
  sprockets (4.0.0.beta2) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (4.0.0.beta2) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (4.0.0.beta2) lib/sprockets/base.rb:66:in `find_asset'
  sprockets (4.0.0.beta2) lib/sprockets/base.rb:73:in `find_all_linked_assets'
  sprockets (4.0.0.beta2) lib/sprockets/manifest.rb:124:in `block in find'
  sprockets (4.0.0.beta2) lib/sprockets/manifest.rb:123:in `find'
  sprockets-rails (3.1.1) lib/sprockets/railtie.rb:50:in `precompiled_assets'
  sprockets-rails (3.1.1) lib/sprockets/railtie.rb:35:in `asset_precompiled?'
  sprockets-rails (3.1.1) lib/sprockets/railtie.rb:250:in `block (3 levels) in <class:Railtie>'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:342:in `precompiled?'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:346:in `raise_unless_precompiled_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:331:in `find_debug_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:212:in `block in lookup_debug_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:225:in `block in resolve_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:224:in `resolve_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:211:in `lookup_debug_asset'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:153:in `block in stylesheet_link_tag'
  sprockets-rails (3.1.1) lib/sprockets/rails/helper.rb:152:in `stylesheet_link_tag'
  app/views/layouts/session.html.haml:9:in `_app_views_layouts_session_html_haml___73016550786083897_70335336018840'
  actionview (5.0.0) lib/action_view/template.rb:158:in `block in render'
  activesupport (5.0.0) lib/active_support/notifications.rb:166:in `instrument'
  actionview (5.0.0) lib/action_view/template.rb:348:in `instrument'
  actionview (5.0.0) lib/action_view/template.rb:156:in `render'
  rack-mini-profiler (0.10.1) lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
  actionview (5.0.0) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
  skylight (0.10.5) lib/skylight/probes/action_view.rb:32:in `block in render_with_layout'
  actionview (5.0.0) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
  activesupport (5.0.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (5.0.0) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.0.0) lib/active_support/notifications.rb:164:in `instrument'
  actionview (5.0.0) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
  skylight (0.10.5) lib/skylight/probes/action_view.rb:31:in `render_with_layout'
  actionview (5.0.0) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (5.0.0) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (5.0.0) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (5.0.0) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (5.0.0) lib/action_view/rendering.rb:103:in `_render_template'
  actionpack (5.0.0) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (5.0.0) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (5.0.0) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  actionpack (5.0.0) lib/action_controller/metal/renderers.rb:144:in `render_to_body'
  actionpack (5.0.0) lib/abstract_controller/rendering.rb:26:in `render'
  actionpack (5.0.0) lib/action_controller/metal/rendering.rb:36:in `render'
  actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (5.0.0) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/this_is_my_username/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (5.0.0) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (5.0.0) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:43:in `render'
  wicked_pdf (1.0.6) lib/wicked_pdf/pdf_helper.rb:22:in `render_with_wicked_pdf'
   () Users/this_is_my_username/.rvm/gems/ruby-2.2.3/bundler/gems/remotipart-88d9a7d55bde/lib/remotipart/render_overrides.rb:16:in `render_with_remotipart'
  responders (2.2.0) lib/action_controller/responder.rb:238:in `default_render'
  responders (2.2.0) lib/action_controller/responder.rb:170:in `to_html'
  responders (2.2.0) lib/action_controller/responder.rb:163:in `respond'
  responders (2.2.0) lib/action_controller/responder.rb:156:in `call'
  responders (2.2.0) lib/action_controller/respond_with.rb:205:in `respond_with'
  devise (4.2.0) app/controllers/devise/sessions_controller.rb:12:in `new'
  actionpack (5.0.0) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  actionpack (5.0.0) lib/abstract_controller/base.rb:188:in `process_action'
  actionpack (5.0.0) lib/action_controller/metal/rendering.rb:30:in `process_action'
  actionpack (5.0.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (5.0.0) lib/active_support/callbacks.rb:126:in `call'
  activesupport (5.0.0) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
  activesupport (5.0.0) lib/active_support/callbacks.rb:455:in `call'
  activesupport (5.0.0) lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
  activesupport (5.0.0) lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
   () Users/this_is_my_username/.rvm/gems/ruby-2.2.3/bundler/gems/rails-observers-3fe157d6cbb5/lib/rails/observers/action_controller/caching/sweeper.rb:24:in `around'
  activesupport (5.0.0) lib/active_support/callbacks.rb:405:in `block in make_lambda'
  activesupport (5.0.0) lib/active_support/callbacks.rb:285:in `block in halting'
  activesupport (5.0.0) lib/active_support/callbacks.rb:447:in `block in around'
  activesupport (5.0.0) lib/active_support/callbacks.rb:455:in `call'
  activesupport (5.0.0) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  activesupport (5.0.0) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  activesupport (5.0.0) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (5.0.0) lib/action_controller/metal/rescue.rb:20:in `process_action'
  actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (5.0.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (5.0.0) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.0.0) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (5.0.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (5.0.0) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
  activerecord (5.0.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (5.0.0) lib/abstract_controller/base.rb:126:in `process'
  actionview (5.0.0) lib/action_view/rendering.rb:30:in `process'
  rack-mini-profiler (0.10.1) lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
  actionpack (5.0.0) lib/action_controller/metal.rb:190:in `dispatch'
  actionpack (5.0.0) lib/action_controller/metal.rb:262:in `dispatch'
  actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:32:in `serve'
  actionpack (5.0.0) lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
  actionpack (5.0.0) lib/action_dispatch/routing/mapper.rb:46:in `serve'
  actionpack (5.0.0) lib/action_dispatch/journey/router.rb:39:in `block in serve'
  actionpack (5.0.0) lib/action_dispatch/journey/router.rb:26:in `serve'
  actionpack (5.0.0) lib/action_dispatch/routing/route_set.rb:725:in `call'
  rack-pjax (1.0.0) lib/rack/pjax.rb:12:in `call'
  rack-attack (4.4.1) lib/rack/attack.rb:107:in `call'
   () Users/this_is_my_username/.rvm/gems/ruby-2.2.3/bundler/gems/remotipart-88d9a7d55bde/lib/remotipart/middleware.rb:32:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (2.0.1) lib/rack/etag.rb:25:in `call'
  rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
  rack (2.0.1) lib/rack/head.rb:12:in `call'
  rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
  rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/cookies.rb:613:in `call'
  activerecord (5.0.0) lib/active_record/migration.rb:552:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
  activesupport (5.0.0) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  activesupport (5.0.0) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
  activesupport (5.0.0) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  airbrake (5.4.3) lib/airbrake/rack/middleware.rb:22:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  railties (5.0.0) lib/rails/rack/logger.rb:36:in `call_app'
  railties (5.0.0) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `block in tagged'
  activesupport (5.0.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `tagged'
  railties (5.0.0) lib/rails/rack/logger.rb:24:in `call'
  sprockets-rails (3.1.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
  request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/request_id.rb:24:in `call'
  rack (2.0.1) lib/rack/method_override.rb:22:in `call'
  rack (2.0.1) lib/rack/runtime.rb:22:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.0) lib/action_dispatch/middleware/static.rb:136:in `call'
  rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
  rack-mini-profiler (0.10.1) lib/mini_profiler/profiler.rb:278:in `call'
  railties (5.0.0) lib/rails/engine.rb:522:in `call'
  rack (2.0.1) lib/rack/handler/webrick.rb:86:in `service'
  /Users/this_is_my_username/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/this_is_my_username/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/this_is_my_username/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

Any thoughts?

**Comment by Schwad** [comment]
Better_errors is highlighting `= stylesheet_link_tag 'application'` in `../layouts/session.html.haml`

**Comment by Schwad** [comment]
<img width="1271" alt="screen shot 2016-08-04 at 8 46 41 am" src="https://cloud.githubusercontent.com/assets/7865030/17394259/0dc0fd40-5a20-11e6-9705-5b12ce88105d.png">


The types of errors I get from running RSpec

**Comment by Schwad** [comment]
This might be a `js-routes` problem, when I comment out js-routes these breaks no longer appear (although I get other ones).

**Comment by Schwad** [comment]
It was js-routes. Ignore and move on. :)
