### ISSUE TITLE
gem load error

### ISSUE THREAD

**Issue by pavan93** [rails/execjs#67]
Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
Backtrace for gem load error is:
C:/Users/pavankumar/.gems/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
C:/Users/pavankumar/.gems/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
C:/Users/pavankumar/.gems/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'

**Comment by M5oul** [comment]
I have same error.
You have to install a JavaScript runtime like Node.js.
